### ISSUE TITLE
Bootable ISO

### ISSUE THREAD

**Issue by spsf64** [neurobin/JLIVECD#1]
Hi, your script is the best!
I just have a problem with the ISO it builds, it just gets bootable on usb stick if I use the default *buntu "startup disk creator" or in windows using "rufus". Any other program (DD, unetbootin, MintStck) will not work... the usb stick won't boot.
I tried to compare the code of UCK (ubuntu customization kit), which makes the ISOs bootable, but could not find any difference...
Any help on this?
Thanks for this great software!

**Comment by neurobin** [comment]
I have tested the ISOs mainly with unetbootin, so it should work.. though I have seen pretty much problems people are facing with unetbootin in linuxmint forums, but I never had any problem of such kind, You should probably test it with different usb stick, nowadays this type of tools (to make a bootable usb) try to own the usb device and configures as they like and sometimes mess it up. So, make your usb fresh and clean i.e delete partition/s on your usb and recreate it with FAT filesystem. You can do this with gnome-disk-utility or gparted or any other tool you like...

**Comment by spsf64** [comment]
I tried many different sticks and formats already.
What is interesting is UCK make the isos's always bootable.
Anyway, I thought you could compare the codes just to be sure the images are created the same way...
Thanks for the reply
Sergio

**Comment by neurobin** [comment]
Ok, I will compare the codes and see if there's any difference...

**Comment by neurobin** [comment]
The process is different. UCK includes almost all kind of checking systems in the final stage, but my script doesn't include that much checking systems in the final stage, whent making squashfs I have not provided any other options than xz compression but that requires mksquashfs version 4.1 or greater and I just adopted the codes to do these tasks from https://help.ubuntu.com/community/LiveCDCustomization , And I tried to make it as simple as I can because I basically use it for personal use. You can try different options if you like, but you will need to have some insight knowledge, i.e modify my codes. If you are interested, The installation directory is /usr/local/JLIVECD and the main script that does this job is /usr/local/JLIVECD/main/custom_desktop  .And for uck, it's /usr/lib/remaster-live-cd.sh .

I will need time to concentrate on this project again and I don't know when I will get the time to do so. I would really appreciate it if someone forked my project for better....

If you are going down the hard way, let me know, I will definitely help you on this...

Anyway, which ISO image are you trying this on?

**Comment by spsf64** [comment]
Thank you for replying and take your time to check the code.
I wish I could help, however I am not a coder or programmer, just keeping a xubuntu respin and using JLivecd.
If you want to take a look, the project is located here:
https://sourceforge.net/projects/uxubos/files/
Best regards
Sergio

**Comment by neurobin** [comment]
I just noticed a peculiar case:
 running sudo fdisk -l in terminal shows device information, see if the usb is in W95 Fat system....if not that might be the problem too...
